#!/bin/bash
cd /mnt/sda1
mv casper live
cd live
rm vmlinuz1
rm initrd1.xz
rm *amd64.squashfs


wget -O /mnt/sda1/live/k-4.9.0-12-amd64.squashfs https://sourceforge.net/projects/egyenesenfatdog64/files/Kernel/4.9/k-4.9.0-12-amd64.squashfs/download

wget -O /mnt/sda1/live/vmlinuz1 https://sourceforge.net/projects/egyenesenfatdog64/files/Kernel/4.9/vmlinuz1/download

wget -O /mnt/sda1/live/initrd1.xz https://sourceforge.net/projects/egyenesenfatdog64/files/Kernel/4.9/initrd1.xz/download

nano /mnt/sda1/syslinux/extlinux/extlinux.conf
echo KESZ A RENDSZERCSERE...
echo READY...
