#!/bin/bash
cd /mnt/sda1
mv live casper
cd live
rm vmlinuz1
rm initrd1.xz
rm *amd64.squashfs

wget -O /mnt/sda1/live/5.4.0-109-lowlatency.squashfs https://sourceforge.net/projects/egyenesenfatdog64/files/Kernel/5.4%20lowlatency/5.4.0-109-lowlatency.squashfs/download

wget -O /mnt/sda1/live/vmlinuz1 https://sourceforge.net/projects/egyenesenfatdog64/files/Kernel/5.4%20lowlatency/vmlinuz1/download

wget -O /mnt/sda1/live/initrd1.xz https://sourceforge.net/projects/egyenesenfatdog64/files/Kernel/5.4%20lowlatency/initrd1.xz/download

nano /mnt/sda1/syslinux/extlinux/extlinux.conf
echo KESZ A RENDSZERCSERE...
echo READY...
