#!/bin/bash
echo ""
echo "Brave-Browser-Stable telepítés..."
echo "**********************************"
apt install brave-browser -y
echo ""
echo "fájlok másolása..."
echo "*******************************************"
mkdir /tmp/xxx/opt
mkdir /tmp/xxx/bin
mkdir /tmp/xxx/usr/bin
mkdir /tmp/xxx/usr/lib
mkdir /tmp/xxx/usr/share/applications
mkdir /tmp/xxx/usr/share/icons
mkdir /tmp/xxx/var/lib/apt
mkdir /tmp/xxx/var/lib/dpkg
mkdir /tmp/xxx/var/log/apt

c -r /mnt/live/memory/changes/upperdir/root/.cache
rm -r /mnt/live/memory/changes/upperdir/var/cache
rm -r /mnt/live/memory/changes/upperdir/tmp
rm -r /mnt/live/memory/changes/upperdir/live

rm -r /live/image/live/07-brave-nightly_latest.squashfs
rm -r /live/image/live/03-brave_stabil_latest.squashfs

echo ""
echo "Hordozható verzió tömörítése..."
echo "*******************************"
mksquashfs /mnt/live/memory/changes/upperdir /live/image/live/03-brave_stabil_latest.squashfs
echo ""
echo "Újraindítás..."
echo "**************"
reboot
