#!/bin/bash
killall Xorg
echo ""
echo "Brave-Browser-Stable telepítés..."
echo "**********************************"
apt install brave-browser -y
echo ""
echo "(upperdir)felesleges fájlok eltávolítása..."
echo "*******************************************"
rm -r /mnt/live/memory/changes/upperdir/mnt
rm -r /mnt/live/memory/changes/upperdir/root/.cache
rm -r /mnt/live/memory/changes/upperdir/var/cache
rm -r /mnt/live/memory/changes/upperdir/tmp
rm -r /mnt/live/memory/changes/upperdir/live

rm -r /live/image/live/07-brave-nightly_latest.squashfs
rm -r /live/image/live/03-brave_stabil_latest.squashfs

echo ""
echo "Hordozható verzió tömörítése..."
echo "*******************************"
mksquashfs /mnt/live/memory/changes/upperdir /live/image/live/03-brave_stabil_latest.squashfs
echo ""
echo "Újraindítás..."
echo "**************"
reboot
