#!/bin/bash
killall Xorg
echo ""
echo "Brave-Browser-Nightly telepítés..."
echo "**********************************"
apt install brave-browser-nightly -y
echo ""
echo "(upperdir)felesleges fájlok eltávolítása..."
echo "*******************************************"
rm -r /mnt/live/memory/changes/upperdir/mnt
rm -r /mnt/live/memory/changes/upperdir/root/.cache
rm -r /mnt/live/memory/changes/upperdir/var/cache
rm -r /mnt/live/memory/changes/upperdir/tmp
rm -r /mnt/live/memory/changes/upperdir/live
rm -r /live/image/live/100-update.squashfs
echo ""
echo "Hordozható verzió tömörítése..."
echo "*******************************"
mksquashfs /mnt/live/memory/changes/upperdir /live/image/live/100-update.squashfs -comp zstd
echo ""
echo "Újraindítás..."
echo "**************"
reboot
