#!/bin/bash
killall Xorg
echo ""
echo "Brave-Browser-Nightly telepítés..."
echo "**********************************"
apt install brave-browser-nightly -y
echo ""
echo "Fájlok másolásasa..."
echo "*******************************************"
mkdir -p /tmp/xxx/opt
mkdir -p /tmp/xxx/bin
mkdir -p /tmp/xxx/usr/bin
mkdir -p /tmp/xxx/usr/lib
mkdir -p /tmp/xxx/usr/share/applications
mkdir -p /tmp/xxx/usr/share/icons
mkdir -p /tmp/xxx/var/lib/apt
mkdir -p /tmp/xxx/var/lib/dpkg
mkdir -p /tmp/xxx/var/log/apt

cp -r /mnt/live/memory/changes/upperdir/opt /tmp/xxx/
cp -r /mnt/live/memory/changes/upperdir/bin /tmp/xxx/
cp -r /mnt/live/memory/changes/upperdir/usr/bin /tmp/xxx/usr/
cp -r /mnt/live/memory/changes/upperdir/usr/lib/ /tmp/xxx/usr/
cp -r /mnt/live/memory/changes/upperdir/usr/share/applications /tmp/xxx/usr/share/
cp -r /mnt/live/memory/changes/upperdir/usr/share/icons /tmp/xxx/usr/share/
cp -r /mnt/live/memory/changes/upperdir/var/lib/apt /tmp/xxx/var/lib/
cp -r /mnt/live/memory/changes/upperdir/var/lib/dpkg /tmp/xxx/var/lib/
cp -r /mnt/live/memory/changes/upperdir/var/log/apt /tmp/xxx/var/log/

rm -r /live/image/live/07-brave-nightly_latest.squashfs
rm -r /live/image/live/03-brave_stabil_latest.squashfs

rm -r /bin/br
wget -O /bin/br https://raw.githubusercontent.com/1NSN-egyenesen/1NSN/main/br
chmod 777 /bin/br

echo ""
echo "Hordozható verzió tömörítése..."
echo "*******************************"
mksquashfs /tmp/xxx /live/image/live/07-brave-nightly_latest.squashfs -comp gzip
echo ""
echo "Újraindítás..."
echo "**************"
reboot
