#!/bin/bash
cd /mnt/sda1
mv casper live
cd live
rm *filesystem.squashfs
rm initrd1.xz
rm vmlinuz1
rm sajat.squashfs
wget -O /mnt/sda1/live/initrd1.xz  https://sourceforge.net/projects/egyenesenfatdog64/files/fatdog/initrd1.xz/download
wget -O /mnt/sda1/live/vmlinuz1 https://sourceforge.net/projects/egyenesenfatdog64/files/fatdog/vmlinuz1/download 
wget -O /mnt/sda1/live/fd64.sfs https://sourceforge.net/projects/egyenesenfatdog64/files/fatdog/m.sfs/download
