#!/bin/sh

wget -O /tmp/linux-firmware-20240709.tar.gz --no-check-certificate --content-disposition https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git/snapshot/linux-firmware-20240709.tgz

tar zxvf linux-firmware-20240709.tgz -C /root/
