#!/bin/bash
apt update && upgrade -y
apt install locales -y
apt install kodi -y
apt install qbittorrent -y 
apt install quiterss -y

mksquashfs /mnt/live/memory/changes/upperdir /mnt/sda2/live/95-update_latest.squashfs -com zstd

reboot
