#!/bin/sh
# while-menu-dialog: a menu driven system information program

# while-menu-dialog: a menu driven system information program

DIALOG_CANCEL=1
DIALOG_ESC=255
HEIGHT=0
WIDTH=0

display_result() {
  dialog --title "$1" \
    --no-collapse \
    --msgbox "$result" 0 0
}

while true; do
  exec 3>&1
  selection=$(dialog \
    --backtitle "1NSN Script			Rendszer ISO letolto script" \
    --title "Menu" \
    --clear \
    --cancel-label "Kilépés" \
    --menu "Kerlek valassz ISO-t:" $HEIGHT $WIDTH 4 \
    "1" "Stretch" \
    "2" "Sid" \
    2>&1 1>&3)
  exit_status=$?
  exec 3>&-
  case $exit_status in
    $DIALOG_CANCEL)
      clear
      echo "Program terminated."
      exit
      ;;
    $DIALOG_ESC)
      clear
      echo "Program aborted." >&2
      exit 1
      ;;
  esac
  case $selection in
    0 )
      clear
      echo "Program terminated."
      ;;
    1 )
      result=$(

wget -O /root/1NSN_StretchDog64_K.4.9.iso https://sourceforge.net/projects/egyenesenfatdog64/files/Stretch64/1NSN_StretchDog64_K.4.9.iso/download

)
      display_result "1NSN_StretchDog64_K.4.9.iso letoltve"
      ;;
    2 )
      result=$(

wget -O /root/1NSN_SidDog64_K.5.10.0-15-rt_eng.iso
https://sourceforge.net/projects/egyenesenfatdog64/files/Sid/1NSN_SidDog64_K.5.10.0-15-rt_eng.iso/download

)
      display_result "1NSN_SidDog64_K.5.10.0-15-rt_eng.iso letoltve"
      ;;
      
    
      
    
     esac
done
