#!/bin/sh
# while-menu-dialog: a menu driven system information program

# while-menu-dialog: a menu driven system information program

DIALOG_CANCEL=1
DIALOG_ESC=255
HEIGHT=0
WIDTH=0

display_result() {
  dialog --title "$1" \
    --no-collapse \
    --msgbox "$result" 0 0
}

while true; do
  exec 3>&1
  selection=$(dialog \
    --backtitle "1NSN Script			Kernel letolto script" \
    --title "Menu" \
    --clear \
    --cancel-label "Kilépés" \
    --menu "Kerlek valassz kernelt:" $HEIGHT $WIDTH 4 \
    "1" "4.9" \
    "2" "5.4" \
    "3" "5.10" \
    "4" "5.18" \
    "5" "extlinux.conf" \
     2>&1 1>&3)
  exit_status=$?
  exec 3>&-
  case $exit_status in
    $DIALOG_CANCEL)
      clear
      echo "Program terminated."
      exit
      ;;
    $DIALOG_ESC)
      clear
      echo "Program aborted." >&2
      exit 1
      ;;
  esac
  case $selection in
    0 )
      clear
      echo "Program terminated."
      ;;
    1 )
      result=$(
cd /mnt/sda1
mv casper live
cd live
rm vmlinuz1
rm initrd1.xz
rm *amd64.squashfs      

wget -O /mnt/sda1/live/k-4.9.0-12-amd64.squashfs https://sourceforge.net/projects/egyenesenfatdog64/files/Kernel/4.9/k-4.9.0-12-amd64.squashfs/download

wget -O /mnt/sda1/live/vmlinuz1 https://sourceforge.net/projects/egyenesenfatdog64/files/Kernel/4.9/vmlinuz1/download

wget -O /mnt/sda1/live/initrd1.xz https://sourceforge.net/projects/egyenesenfatdog64/files/Kernel/4.9/initrd1.xz/download
)
      display_result "4.9 Kernel letoltve!"
      ;;
    2 )
      result=$(
cd /mnt/sda1
mv live casper
cd casper
rm vmlinuz1
rm initrd1.xz
rm *amd64.squashfs

wget -O /mnt/sda1/casper/5.4.0-109-lowlatency-amd64.squashfs https://sourceforge.net/projects/egyenesenfatdog64/files/Kernel/5.4%20lowlatency/5.4.0-109-lowlatency.squashfs/download

wget -O /mnt/sda1/casper/vmlinuz1 https://sourceforge.net/projects/egyenesenfatdog64/files/Kernel/5.4%20lowlatency/vmlinuz1/download

wget -O /mnt/sda1/casper/initrd1.xz https://sourceforge.net/projects/egyenesenfatdog64/files/Kernel/5.4%20lowlatency/initrd1.xz/download



)
      display_result "5.4 Kernel letoltve"
      ;;
      
    3 )
      result=$(
cd /mnt/sda1
mv casper live
cd live
rm vmlinuz1
rm initrd1.xz
rm *amd64.squashfs

wget -O /mnt/sda1/live/k-5.10.0-15-rt-amd64.squashfs https://sourceforge.net/projects/egyenesenfatdog64/files/Kernel/5.10-rt/k-5.10.0-15-rt-amd64.squashfs/download

wget -O /mnt/sda1/live/vmlinuz1 https://sourceforge.net/projects/egyenesenfatdog64/files/Kernel/5.10-rt/vmlinuz1/download

wget -O /mnt/sda1/live/initrd1.xz https://sourceforge.net/projects/egyenesenfatdog64/files/Kernel/5.10-rt/initrd1.xz/download
)
      display_result "5.10 Kernel letoltve!"
      ;;
    4 )
      result=$(
cd /mnt/sda1
mv casper live
cd live
rm vmlinuz1
rm initrd1.xz
rm *amd64.squashfs

wget -O /mnt/sda1/live/k-5.18.0-2-rt-amd64.squashfs https://sourceforge.net/projects/egyenesenfatdog64/files/Kernel/5.18-rt/k-5.18.0-4-amd64.squashfs/download

wget -O /mnt/sda1/live/vmlinuz1 https://sourceforge.net/projects/egyenesenfatdog64/files/Kernel/5.18-rt/vmlinuz1/download

wget -O /mnt/sda1/live/initrd1.xz https://sourceforge.net/projects/egyenesenfatdog64/files/Kernel/5.18-rt/initrd1.xz/download
)
      display_result "5.18 Kernel letoltve!"
      ;;  
    
      5 )
      result=$(
geany /mnt/sda1/syslinux/extlinux/extlinux.conf
)
      display_result "extlinux.conf - konfiguralva"
     esac
done
