#!/bin/bash

wget -O /bin/iso --no-check-certificate --content-disposition https://raw.githubusercontent.com/1NSN-egyenesen/1NSN/main/iso
chmod 777 /bin/iso

wget -O /bin/cache --no-check-certificate --content-disposition https://raw.githubusercontent.com/1NSN-egyenesen/1NSN/main/cache
chmod 777 /bin/cache

wget -O /bin/wine32 --no-check-certificate --content-disposition https://raw.githubusercontent.com/1NSN-egyenesen/1NSN/main/wine32
chmod 777 /bin/wine32

wget -O /bin/rendszer --no-check-certificate --content-disposition https://raw.githubusercontent.com/1NSN-egyenesen/1NSN/main/rendszer
chmod 777 /bin/rendszer

wget -O /bin/kernel --no-check-certificate --content-disposition https://raw.githubusercontent.com/1NSN-egyenesen/1NSN/main/kernel
chmod 777 /bin/kernel

wget -O /bin/firmware --no-check-certificate --content-disposition https://raw.githubusercontent.com/1NSN-egyenesen/1NSN/main/firmware
chmod 777 /bin/firmware

wget -O /bin/parancslista --no-check-certificate --content-disposition https://raw.githubusercontent.com/1NSN-egyenesen/1NSN/main/parancslista
chmod 777 /bin/parancslista

wget -O /bin/xmt --no-check-certificate --content-disposition https://raw.githubusercontent.com/1NSN-egyenesen/1NSN/main/xmt
chmod 777 /bin/xmt

wget -O /bin/epito --no-check-certificate --content-disposition https://raw.githubusercontent.com/1NSN-egyenesen/1NSN/main/epito
chmod 777 /bin/epito

wget -O /bin/go --no-check-certificate --content-disposition https://raw.githubusercontent.com/1NSN-egyenesen/1NSN/main/go
chmod 777 /bin/go

wget -O /bin/conf https://raw.githubusercontent.com/1NSN-egyenesen/1NSN/main/conf
chmod 777 /bin/conf

wget -O /bin/m https://raw.githubusercontent.com/1NSN-egyenesen/1NSN/main/m
chmod 777 /bin/m

echo "Scriptek letoltese kesz..."
echo "Ready..."
