#!/bin/sh
# while-menu-dialog: a menu driven system information program

# while-menu-dialog: a menu driven system information program

DIALOG_CANCEL=1
DIALOG_ESC=255
HEIGHT=0
WIDTH=0

display_result() {
  dialog --title "$1" \
    --no-collapse \
    --msgbox "$result" 0 0
}

while true; do
  exec 3>&1
  selection=$(dialog \
    --backtitle "1NSN Script			Rendszer letolto script" \
    --title "Menu" \
    --clear \
    --cancel-label "Kilépés" \
    --menu "Kerlek valassz rendszert:" $HEIGHT $WIDTH 4 \
    "1" "Stretch" \
    "2" "Sid + 5.4 low-kernel" \
    "3" "extlinux.conf" \
    "4" "Ventoy" \
    "5" "Avidemux" \
    2>&1 1>&3)
  exit_status=$?
  exec 3>&-
  case $exit_status in
    $DIALOG_CANCEL)
      clear
      echo "Program terminated."
      exit
      ;;
    $DIALOG_ESC)
      clear
      echo "Program aborted." >&2
      exit 1
      ;;
  esac
  case $selection in
    0 )
      clear
      echo "Program terminated."
      ;;
    1 )
      result=$(
cd /mnt/sda1
mkdir live
mv casper live
cd live
rm *filesystem.squashfs

wget -O /live/image/live/02-stretch-update.squashfs https://sourceforge.net/projects/egyenesenfatdog64/files/Stretch64/02-stretch-update.squashfs/download
wget -O /live/image/live/01-filesystem_libgbm1-update_comp-gz.squashfs https://sourceforge.net/projects/egyenesenfatdog64/files/Stretch64/01-filesystem_libgbm1-update_comp-gz.squashfs/download

)
      display_result ""
      ;;
    2 )
      result=$(
cd /mnt/sda1/live
rm *filesystem.squashfs
rm vmlinuz1
rm initrd1.xz
rm *amd64.squashfs

wget -O /live/image/live/01-alap-filesystem.squashfs https://sourceforge.net/projects/egyenesenfatdog64/files/Sid/01-alap-filesystem.squashfs/download
wget -O /live/image/live/02-1nsn-conf.squashfs https://sourceforge.net/projects/egyenesenfatdog64/files/Sid/02-1nsn-conf.squashfs/download
wget -O /live/image/live/5.4.0-109-lowlatency-amd64.squashfs https://sourceforge.net/projects/egyenesenfatdog64/files/Kernel/5.4-low/5.4.0-109-lowlatency-amd64.squashfs/download
wget -O /live/image/live/vmlinuz1 https://sourceforge.net/projects/egyenesenfatdog64/files/Kernel/5.4-low/vmlinuz1/download
wget -O /live/image/live/initrd1.xz https://sourceforge.net/projects/egyenesenfatdog64/files/Kernel/5.4-low/initrd1.xz/download
wget -O /live/image/live/99-linux-firmware_1.187.34.squashfs https://sourceforge.net/projects/egyenesenfatdog64/files/Firmware/99-linux-firmware_1.187.34.squashfs/download
)
      display_result ""
      ;;
      
   3 )
      result=$(
wget -O /mnt/sda1/syslinux/extlinux/extlinux.conf https://raw.githubusercontent.com/1NSN-egyenesen/1NSN/main/extlinux.conf

)
      display_result ""
      ;;  
    
    4 )
      result=$(
wget -O /mnt/sda1/live/12-ventoy_1.0.77.squashfs https://sourceforge.net/projects/egyenesenfatdog64/files/app/12-ventoy_1.0.77.squashfs/download

)
    display_result ""
      ;;  
     
    5 )
      result=$(
wget -O /mnt/sda1/live/11-avidemux_2.8_all_deb.squashfs https://sourceforge.net/projects/egyenesenfatdog64/files/app/11-avidemux_2.8_all_deb.squashfs/download

)
    display_result ""
      ;;  
     
     esac
done
