#!/bin/sh


DIALOG_CANCEL=1
DIALOG_ESC=255
HEIGHT=0
WIDTH=0

display_result() {
  dialog --title "$1" \
    --no-collapse \
    --msgbox "$result" 0 0
}

while true; do
  exec 3>&1
  selection=$(dialog \
    --backtitle "1NSN Script			Rendszer és App letolto script" \
    --title "Menu" \
    --clear \
    --cancel-label "Kilépés" \
    --menu "Kerlek valassz rendszert:" $HEIGHT $WIDTH 4 \
    "1" "Wine" \
    "2" "Ceres - repo" \
    "3" "Kodi" \
    "4" "Ventoy" \
    "5" "Avidemux" \
    "6" "Qbittorrent" \
    "7" "MKVToolnix" \
    "8" "no save copy2ram" \
    2>&1 1>&3)
  exit_status=$?
  exec 3>&-
  case $exit_status in
    $DIALOG_CANCEL)
      clear
      echo "Program terminated."
      exit
      ;;
    $DIALOG_ESC)
      clear
      echo "Program aborted." >&2
      exit 1
      ;;
  esac
  case $selection in
    0 )
      clear
      echo "Program terminated."
      ;;
    1 )
      result=$(
wget -O /live/image/live/98-wine_8.0_Repack4.squashfs https://sourceforge.net/projects/egyenesenfatdog64/files/app/98-wine_8.0_Repack4.squashfs/download

)
      display_result "Letöltve! Indítsd újra a rendszert!"
      ;;
    2 )
      result=$(
      cp -r /home/1NSN/scriptek/sources.list /etc/apt/sources.list
)
      display_result "Letöltve! Indítsd újra a rendszert!"
      ;;
      
   3 )
      result=$(
rm -r /live/image/live/25-kodi_latest.squashfs
wget -O /live/image/live/25-kodi_latest.squashfs https://sourceforge.net/projects/egyenesenfatdog64/files/app/25-kodi_latest.squashfs/download

)
      display_result "Letöltés kész! Indítsd újra a rendszert!"
      ;;  
    
    4 )
      result=$(
wget -O /live/image/live/12-ventoy_1.0.77.squashfs https://sourceforge.net/projects/egyenesenfatdog64/files/app/12-ventoy_1.0.77.squashfs/download

)
    display_result "Letöltve! Indítsd újra a rendszert!"
      ;;  
     
    5 )
      result=$(
wget -O /live/image/live/11-avidemux_2.8_all_deb.squashfs https://sourceforge.net/projects/egyenesenfatdog64/files/app/11-avidemux_2.8_all_deb.squashfs/download

)
    display_result "Letöltve! Indítsd újra a rendszert!"
      ;;  
     
     
     6 )
      result=$(
rm -r /live/image/live/09-qbittorrent_latest.squashfs

wget -O /live/image/live/09-qbittorrent_latest.squashfs https://sourceforge.net/projects/egyenesenfatdog64/files/app/09-qbittorrent_latest.squashfs/download

)
     display_result "Letöltve! Indítsd újra a rendszert!"
      ;;  
     
     7 )
      result=$(
rm -r /live/image/live/08-mkvtoolnix_latest.squashfs
wget -O /live/image/live/08-mkvtoolnix_latest.squashfs https://sourceforge.net/projects/egyenesenfatdog64/files/app/08-mkvtoolnix_latest.squashfs/download
)
     display_result "Letöltve! Indítsd újra a rendszert!"
      ;;  

     8 )
      result=$(
rm -r /live/image/syslinux/extlinux/extlinux.conf
wget -O /live/image/syslinux/extlinux/extlinux.conf https://raw.githubusercontent.com/1NSN-egyenesen/1NSN/main/extlinux.conf

)
      display_result "Letöltve! Indítsd újra a rendszert!"
     
     

esac
done

