#!/bin/sh
# while-menu-dialog: a menu driven system information program

# while-menu-dialog: a menu driven system information program

DIALOG_CANCEL=1
DIALOG_ESC=255
HEIGHT=0
WIDTH=0

display_result() {
  dialog --title "$1" \
    --no-collapse \
    --msgbox "$result" 0 0
}

while true; do
  exec 3>&1
  selection=$(dialog \
    --backtitle "1NSN Script			Rendszer letolto script" \
    --title "Menu" \
    --clear \
    --cancel-label "Kilépés" \
    --menu "Kerlek valassz rendszert:" $HEIGHT $WIDTH 4 \
    "1" "Stretch" \
    "2" "Sid + 5.4 low-kernel" \
    "3" "Sid-frissites" \
    "4" "Ceres" \
    2>&1 1>&3)
  exit_status=$?
  exec 3>&-
  case $exit_status in
    $DIALOG_CANCEL)
      clear
      echo "Program terminated."
      exit
      ;;
    $DIALOG_ESC)
      clear
      echo "Program aborted." >&2
      exit 1
      ;;
  esac
  case $selection in
    0 )
      clear
      echo "Program terminated."
      ;;
    1 )
      result=$(
cd /mnt/sda1
mkdir live
mv casper live
cd live
rm *filesystem.squashfs

wget -O /mnt/sda1/live/02-1nsn-conf.squashfs https://sourceforge.net/projects/egyenesenfatdog64/files/Stretch64/m-stretch.squashfs/download
wget -O /mnt/sda1/live/01-filesystem.squashfs https://sourceforge.net/projects/egyenesenfatdog64/files/Stretch64/01-filesystem.squashfs/download

)
      display_result ""
      ;;
    2 )
      result=$(
cd /mnt/sda1/live
rm *filesystem.squashfs
rm vmlinuz1
rm initrd1.xz
rm *amd64.squashfs

wget -O /mnt/sda1/live/01-latest-filesystem.squashfs https://sourceforge.net/projects/egyenesenfatdog64/files/Sid/01-latest-filesystem.squashfs/download
wget -O /mnt/sda1/live/02-1nsn-conf.squashfs https://github.com/1NSN-egyenesen/1NSN/raw/main/02-1nsn-conf.squashfs
wget -O /mnt/sda1/live/10-google-latest.squashfs https://sourceforge.net/projects/egyenesenfatdog64/files/app/10-google-latest.squashfs/download
wget -O /mnt/sda1/live/5.4.0-109-lowlatency-amd64.squashfs https://sourceforge.net/projects/egyenesenfatdog64/files/Kernel/5.4-low/5.4.0-109-lowlatency-amd64.squashfs/download
wget -O /mnt/sda1/live/vmlinuz1 https://sourceforge.net/projects/egyenesenfatdog64/files/Kernel/5.4-low/vmlinuz1/download
wget -O /mnt/sda1/live/initrd1.xz https://sourceforge.net/projects/egyenesenfatdog64/files/Kernel/5.4-low/initrd1.xz/download
wget -O /mnt/sda1/live/99-linux-firmware_1.187.34.squashfs https://sourceforge.net/projects/egyenesenfatdog64/files/Firmware/99-linux-firmware_1.187.34.squashfs/download
)
      display_result ""
      ;;
      
    3 )
      result=$(
cd /mnt/sda1/live
rm *filesystem.squashfs

wget -O /mnt/sda1/live/01-latest-filesystem.squashfs https://sourceforge.net/projects/egyenesenfatdog64/files/Sid/01-latest-filesystem.squashfs/download
)
      display_result ""
      ;;
      
    4 )
      result=$(
cd /mnt/sda1
mkdir live
mv casper live
cd live
rm *filesystem.squashfs

wget -O /mnt/sda1/live/01-filesystem.squashfs https://sourceforge.net/projects/egyenesenfatdog64/files/ceres/01-filesystem.squashfs/download
wget -O /mnt/sda1/live/02-1nsn-conf-ceres.squashfs https://sourceforge.net/projects/egyenesenfatdog64/files/ceres/02-1nsn-conf-ceres.squashfs/download
)
      display_result ""
      ;;
      
    
     esac
done
