#!/bin/bash


mkdir -p /tmp/xxx/var/lib
mkdir -p /tmp/xxx/var/log

cp -r /mnt/live/memory/changes/upperdir/var/lib/apt /tmp/xxx/var/lib/
cp -r /mnt/live/memory/changes/upperdir/var/lib/dpkg /tmp/xxx/var/lib/
cp -r /mnt/live/memory/changes/upperdir/var/log/apt /tmp/xxx/var/log/

mksquashfs /tmp/xxx/ /live/image/live/31-dpkg_status.squashfs
