#!/bin/bash
echo ""
echo "Csomagkezelő,frissítés..."
echo "*************************"
apt update && dist-upgrade
echo ""
echo "Újabb csomagok kilistázás..."
echo "****************************"
apt list --upgradable
echo ""
echo "*****************************************************************************"
apt policy brave-browser-nightly
echo "*****************************************************************************"
apt policy qbittorrent
echo "*****************************************************************************"
echo "Rendszer frissítés lehetősége..."
echo "********************************"
apt upgrade 
apt install kodi && qbittorrent && locales

echo ""
echo "*****Script by .:1NSN:.*****"
echo ""

