#!/bin/bash
echo ""
echo "Csomagkezelő,frissítés..."
echo "*************************"
apt update && upgrade
echo ""
echo "Újabb csomagok kilistázás..."
echo "****************************"
apt list --upgradable
echo ""
echo "**********************************************************************"
apt policy brave-browser-nightly
echo "**********************************************************************"
apt policy qbittorrent
echo "**********************************************************************"
apt policy kodi
echo "**********************************************************************"
apt policy signal
echo "**********************************************************************"
apt policy atox
echo "**********************************************************************"
echo "Rendszer frissítés lehetősége..."
echo "********************************"
apt upgrade 
echo ""
echo "*****Script by .:1NSN:.*****"
echo ""

