#!/bin/bash
echo ""
echo "Csomagkezelő,frissítés..."
apt update && upgrade

echo "Újabb csomagok..."
echo ""
apt list --upgradable
echo ""
echo "Válassz alkalmazást..." 
echo ""
echo "Brave-Browser-Nightly..."
echo ""
apt install brave-browser-nightly
echo ""
echo "Signal..."
apt install signal-desktop
echo ""
echo "Utox.."
apt install utox
echo ""
echo "Qbittorrent..."
apt install qbittorrent
echo ""
echo "Kodi..."
apt install kodi 
echo ""
echo ""
echo "Hordozható verzió elkészítése..."
echo ""
echo "Előző verzió eltávolítása..."
rm -r /live/image/live/100-update.squashfs
echo ""
echo "Tömörítés..."
mksquashfs /mnt/live/memory/changes/upperdir /live/image/live/100-update.squashfs -comp zstd
echo ""
echo "***************Script by .:1NSN:.*************************"
echo "*Elkészült a frissítés,kérlek indítsd újra a rendszert...*"
echo "**********************************************************"
