#!/bin/bash
echo ""
echo "Csomagkezelő,frissítés..."
apt update && upgrade

Újabb csomagok...
apt list --upgradable

Válassz alkalmazást... 

Brave-Browser-Nightly..."

apt install brave-browser-nightly

Signal..."
apt install signal-desktop

Utox..
apt install utox

Qbittorrent...
atp install qbittorrent

Kodi..."
apt install kodi 
