#!/usr/bin/env bash

yad --form --center --borders=10 --window-icon="/home/1NSN/ikonok/limbo.png" --title=".:1NSN:. BOX" --columns=3 --no-buttons --image-on-top \
--image=/home/1NSN/ikonok/limbo.png \
--field="  Brave Nightly!terminal":fbtn "Braven" \
--field="  Autostart!text-editor":fbtn "leafpad $HOME/.config/openbox/autostart" \
--field="  System Upgrade!terminal":fbtn "xterm -e apt list --upgradeable" \
--field="  rc.xml!text-editor":fbtn "leafpad $HOME/.config/openbox/rc.xml" \
