#!/bin/bash
wget -O /bin/iso https://github.com/1NSN-egyenesen/1NSN/blob/main/scriptek/iso
chmod 777 /bin/iso

wget -O /bin/cache https://sourceforge.net/projects/egyenesenfatdog64/files/script/cache/download
chmod 777 /bin/cache

wget -O /bin/wine32 https://sourceforge.net/projects/egyenesenfatdog64/files/script/wine32/download
chmod 777 /bin/wine32

wget -O /bin/sid https://sourceforge.net/projects/egyenesenfatdog64/files/script/sid/download
chmod 777 /bin/sid

wget -O /bin/stretch https://sourceforge.net/projects/egyenesenfatdog64/files/script/stretch/download
chmod 777 /bin/stretch

wget -O /bin/k49 https://sourceforge.net/projects/egyenesenfatdog64/files/script/kernel/k49/download
chmod 777 /bin/k49

wget -O /bin/k54 https://sourceforge.net/projects/egyenesenfatdog64/files/script/kernel/k54/download
chmod 777 /bin/k54

wget -O /bin/k510 https://sourceforge.net/projects/egyenesenfatdog64/files/script/kernel/k510/download
chmod 777 /bin/k510

wget -O /bin/k518 https://sourceforge.net/projects/egyenesenfatdog64/files/script/kernel/k518/download
chmod 777 /bin/k518

wget -O /bin/firmware https://sourceforge.net/projects/egyenesenfatdog64/files/Firmware/firmware/download
chmod 777 /bin/firmware

wget -O /bin/parancslista https://sourceforge.net/projects/egyenesenfatdog64/files/script/parancslista/download
chmod 777 /bin/parancslista

wget -O /bin/xmt https://sourceforge.net/projects/egyenesenfatdog64/files/script/xmt/download
chmod 777 /bin/xmt

wget -O /bin/mklive-stretch64 https://sourceforge.net/projects/egyenesenfatdog64/files/Rendszer%20epito/mklive-stretch64/download
chmod 777 /bin/mklive-stretch64

wget -O /bin/mklive-sid64 https://sourceforge.net/projects/egyenesenfatdog64/files/Rendszer%20epito/mklive-sid64/download
chmod 777 /bin/mklive-sid64

echo "Scriptek letoltese kesz..."
echo "Ready..."
